services:
  persistence-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdf-persistence-service:latest
    container_name: pdf-persistence-service
    restart: unless-stopped
    ports:
      - "8003:8000"
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.persistence-service.rule=Host(`persistence.localhost`)"
      - "traefik.http.routers.persistence-service.entrypoints=web"
      - "traefik.http.services.persistence-service.loadbalancer.server.port=8000"
    networks:
      - mired

networks:
  mired:
    external: true
